/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegmentosRouteImport } from './routes/segmentos'
import { Route as RecompraRouteImport } from './routes/recompra'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DocumentacionRouteImport } from './routes/documentacion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalisisIaRouteImport } from './routes/analisis-ia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecompraIndexRouteImport } from './routes/recompra.index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as RecompraClientIdRouteImport } from './routes/recompra.$clientId'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'

const SegmentosRoute = SegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompraRoute = RecompraRouteImport.update({
  id: '/recompra',
  path: '/recompra',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacionRoute = DocumentacionRouteImport.update({
  id: '/documentacion',
  path: '/documentacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisIaRoute = AnalisisIaRouteImport.update({
  id: '/analisis-ia',
  path: '/analisis-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompraIndexRoute = RecompraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecompraRoute,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const RecompraClientIdRoute = RecompraClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => RecompraRoute,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis-ia': typeof AnalisisIaRoute
  '/dashboard': typeof DashboardRoute
  '/documentacion': typeof DocumentacionRoute
  '/landing': typeof LandingRoute
  '/leads': typeof LeadsRouteWithChildren
  '/recompra': typeof RecompraRouteWithChildren
  '/segmentos': typeof SegmentosRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/recompra/$clientId': typeof RecompraClientIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/recompra/': typeof RecompraIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisis-ia': typeof AnalisisIaRoute
  '/dashboard': typeof DashboardRoute
  '/documentacion': typeof DocumentacionRoute
  '/landing': typeof LandingRoute
  '/segmentos': typeof SegmentosRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/recompra/$clientId': typeof RecompraClientIdRoute
  '/leads': typeof LeadsIndexRoute
  '/recompra': typeof RecompraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisis-ia': typeof AnalisisIaRoute
  '/dashboard': typeof DashboardRoute
  '/documentacion': typeof DocumentacionRoute
  '/landing': typeof LandingRoute
  '/leads': typeof LeadsRouteWithChildren
  '/recompra': typeof RecompraRouteWithChildren
  '/segmentos': typeof SegmentosRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/recompra/$clientId': typeof RecompraClientIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/recompra/': typeof RecompraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis-ia'
    | '/dashboard'
    | '/documentacion'
    | '/landing'
    | '/leads'
    | '/recompra'
    | '/segmentos'
    | '/leads/$leadId'
    | '/recompra/$clientId'
    | '/leads/'
    | '/recompra/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisis-ia'
    | '/dashboard'
    | '/documentacion'
    | '/landing'
    | '/segmentos'
    | '/leads/$leadId'
    | '/recompra/$clientId'
    | '/leads'
    | '/recompra'
  id:
    | '__root__'
    | '/'
    | '/analisis-ia'
    | '/dashboard'
    | '/documentacion'
    | '/landing'
    | '/leads'
    | '/recompra'
    | '/segmentos'
    | '/leads/$leadId'
    | '/recompra/$clientId'
    | '/leads/'
    | '/recompra/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisisIaRoute: typeof AnalisisIaRoute
  DashboardRoute: typeof DashboardRoute
  DocumentacionRoute: typeof DocumentacionRoute
  LandingRoute: typeof LandingRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  RecompraRoute: typeof RecompraRouteWithChildren
  SegmentosRoute: typeof SegmentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segmentos': {
      id: '/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof SegmentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompra': {
      id: '/recompra'
      path: '/recompra'
      fullPath: '/recompra'
      preLoaderRoute: typeof RecompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacion': {
      id: '/documentacion'
      path: '/documentacion'
      fullPath: '/documentacion'
      preLoaderRoute: typeof DocumentacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis-ia': {
      id: '/analisis-ia'
      path: '/analisis-ia'
      fullPath: '/analisis-ia'
      preLoaderRoute: typeof AnalisisIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompra/': {
      id: '/recompra/'
      path: '/'
      fullPath: '/recompra/'
      preLoaderRoute: typeof RecompraIndexRouteImport
      parentRoute: typeof RecompraRoute
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/recompra/$clientId': {
      id: '/recompra/$clientId'
      path: '/$clientId'
      fullPath: '/recompra/$clientId'
      preLoaderRoute: typeof RecompraClientIdRouteImport
      parentRoute: typeof RecompraRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
  }
}

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface RecompraRouteChildren {
  RecompraClientIdRoute: typeof RecompraClientIdRoute
  RecompraIndexRoute: typeof RecompraIndexRoute
}

const RecompraRouteChildren: RecompraRouteChildren = {
  RecompraClientIdRoute: RecompraClientIdRoute,
  RecompraIndexRoute: RecompraIndexRoute,
}

const RecompraRouteWithChildren = RecompraRoute._addFileChildren(
  RecompraRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisisIaRoute: AnalisisIaRoute,
  DashboardRoute: DashboardRoute,
  DocumentacionRoute: DocumentacionRoute,
  LandingRoute: LandingRoute,
  LeadsRoute: LeadsRouteWithChildren,
  RecompraRoute: RecompraRouteWithChildren,
  SegmentosRoute: SegmentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
